export const STORY_ARCHIVE = 'STORY_ARCHIVE';
export const STORIES_FETCH = 'STORIES_FETCH';
export const STORIES_FETCH_ERROR = 'STORIES_FETCH_ERROR';
export const STORIES_ADD = 'STORIES_ADD';
export const ADD_ARCHIVED_ARTICLES = 'ADD_ARCHIVED_ARTICLES';
export const DELETE_ARCHIVED_ARTICLE = 'DELETE_ARCHIVED_ARTICLE';
export const EDIT_ARCHIVED_ARTICLE = 'EDIT_ARCHIVED_ARTICLE';
export const ADD_ARCHIVED_ERROR = 'ADD_ARCHIVED_ERROR';
